version: '2.1'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
#    ports:
#      - "5432:5432"
#    networks:
#      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  app:
    image: maryjein/bestseller:latest
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:5432/test_db
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy